# 這裏的東西專放一些短期實驗用的玩意，故不穩定，隨時會改
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: see2-lab
  namespace: flux-system
spec:
  interval: 3m0s
  ref:
    branch: deploy
  secretRef:
    name: flux-system
  url: https://github.com/see2-club/see2-lab.git
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: see2-lab
  namespace: flux-system
spec:
  image: ghcr.io/see2-club/see2-lab
  interval: 3m0s
  secretRef:
    name: ghcr-login-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: see2-lab
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: see2-lab
  filterTags:
    pattern: '^.+-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
# Deploy - Dev
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: see2-lab
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: deploy
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: deploy
  interval: 3m0s
  sourceRef:
    kind: GitRepository
    name: see2-lab
  update:
    path: ./manifests/overlays/dev
    strategy: Setters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: see2-lab-depoly-dev
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./manifests/overlays/dev
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: see2-lab
