---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-tenant
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: production
  secretRef:
    name: flux-system
  url: https://github.com/see2-club/flux-gke-cluster.git
