---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-tenant
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./instances/production
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: system-tenant
