---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: automate-update
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./automate-update/gke-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-system
