---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infrastructures
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
    # branch: gke-prod
  secretRef:
    name: flux-system
  url: https://github.com/see2-club/flux-cluster-infrastructures.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructures-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/gke-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: infrastructures
